-- Onyx Premium Carwash — greenfield schema
--
-- Run this entire file once in the Supabase SQL editor on a NEW project
-- (Dashboard → SQL Editor → New query → paste → Run).
-- It creates live tables, RLS, the gallery storage bucket, and seed rows
-- the public site expects (shop info, hours, CMS singletons).
--
-- Do not run this to "upgrade" an existing Onyx database. Existing projects
-- already have these tables; use the feature patches in this folder instead:
--   admin-profiles.sql, gallery.sql, faqs.sql, about.sql, welcome.sql,
--   legal.sql, appointments.sql, shop-info-drop-address.sql
-- rename-catalog.sql is only for the original rename from categories1/services1.
--
-- Live tables: shop_info, shop_hours, categories, services, site_announcements,
-- gallery_images, faqs, about_content, welcome_content, legal_documents,
-- admin_profiles, appointment
--
-- Legacy tables (categories_legacy, all_services, services_packages, …) are
-- intentionally omitted.

-- ---------------------------------------------------------------------------
-- Shop
-- ---------------------------------------------------------------------------

create table if not exists public.shop_info (
  id bigint primary key default 1 check (id = 1),
  name text not null,
  phone text,
  email text,
  address1 text,
  address2 text,
  city text,
  state text,
  zip text,
  latitude double precision,
  longitude double precision,
  description text,
  description2 text,
  facebook text,
  instagram text,
  twitter text,
  created_at timestamptz default now()
);

create table if not exists public.shop_hours (
  id bigint generated by default as identity primary key,
  shop_id bigint not null references public.shop_info (id) on delete cascade,
  day_name text not null,
  open_time time,
  close_time time,
  is_closed boolean default false,
  unique (shop_id, day_name)
);

alter table public.shop_info enable row level security;
alter table public.shop_hours enable row level security;

drop policy if exists "Public can view shop info" on public.shop_info;
create policy "Public can view shop info"
  on public.shop_info
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can update shop info" on public.shop_info;
create policy "Authenticated can update shop info"
  on public.shop_info
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Public can view shop hours" on public.shop_hours;
create policy "Public can view shop hours"
  on public.shop_hours
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can update shop hours" on public.shop_hours;
create policy "Authenticated can update shop hours"
  on public.shop_hours
  for update
  to authenticated
  using (true)
  with check (true);

grant select on table public.shop_info to anon, authenticated;
grant update on table public.shop_info to authenticated;
grant select on table public.shop_hours to anon, authenticated;
grant update on table public.shop_hours to authenticated;

insert into public.shop_info (
  id,
  name,
  phone,
  email,
  address1,
  city,
  state,
  zip,
  latitude,
  longitude,
  description,
  description2
)
select
  1,
  'Onyx Premium Carwash',
  '(555) 000-0000',
  'hello@example.com',
  '123 Main Street',
  'Chicago',
  'IL',
  '60601',
  41.882657,
  -87.623303,
  'Premium hand car wash.',
  'The Gold Standard of Clean'
where not exists (select 1 from public.shop_info where id = 1);

insert into public.shop_hours (shop_id, day_name, open_time, close_time, is_closed)
select 1, seed.day_name, seed.open_time, seed.close_time, seed.is_closed
from (
  values
    ('Monday',    time '08:00', time '18:00', false),
    ('Tuesday',   time '08:00', time '18:00', false),
    ('Wednesday', time '08:00', time '18:00', false),
    ('Thursday',  time '08:00', time '18:00', false),
    ('Friday',    time '08:00', time '18:00', false),
    ('Saturday',  time '08:00', time '17:00', false),
    ('Sunday',    null::time,   null::time,   true)
) as seed(day_name, open_time, close_time, is_closed)
where not exists (select 1 from public.shop_hours);

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sort_order integer,
  created_at timestamptz default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  notes text,
  category_id bigint references public.categories (id) on delete restrict,
  card_layout text check (
    card_layout is null
    or card_layout in ('layout1', 'layout2', 'layout3', 'layout4')
  ),
  layout1_data jsonb,
  layout2_data jsonb,
  layout3_data text,
  layout4_data jsonb,
  sort_order integer not null default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

create index if not exists services_category_id_idx
  on public.services (category_id, sort_order, id);

alter table public.categories enable row level security;
alter table public.services enable row level security;

drop policy if exists "Public can view categories" on public.categories;
create policy "Public can view categories"
  on public.categories
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can insert categories" on public.categories;
create policy "Authenticated can insert categories"
  on public.categories
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated can update categories" on public.categories;
create policy "Authenticated can update categories"
  on public.categories
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated can delete categories" on public.categories;
create policy "Authenticated can delete categories"
  on public.categories
  for delete
  to authenticated
  using (true);

drop policy if exists "Public can view active services" on public.services;
create policy "Public can view active services"
  on public.services
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Authenticated can view all services" on public.services;
create policy "Authenticated can view all services"
  on public.services
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated can insert services" on public.services;
create policy "Authenticated can insert services"
  on public.services
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated can update services" on public.services;
create policy "Authenticated can update services"
  on public.services
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated can delete services" on public.services;
create policy "Authenticated can delete services"
  on public.services
  for delete
  to authenticated
  using (true);

grant select on table public.categories to anon, authenticated;
grant insert, update, delete on table public.categories to authenticated;
grant select on table public.services to anon, authenticated;
grant insert, update, delete on table public.services to authenticated;

insert into public.categories (name, slug, sort_order)
select 'Washes', 'washes', 1
where not exists (select 1 from public.categories);

-- ---------------------------------------------------------------------------
-- Announcements
-- ---------------------------------------------------------------------------

create table if not exists public.site_announcements (
  id bigint generated by default as identity primary key,
  message text,
  link_url text,
  sort_order integer default 0,
  is_active boolean default true,
  created_at timestamptz not null default now()
);

create index if not exists site_announcements_sort_order_idx
  on public.site_announcements (sort_order, id);

alter table public.site_announcements enable row level security;

drop policy if exists "Public can view active announcements" on public.site_announcements;
create policy "Public can view active announcements"
  on public.site_announcements
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Authenticated can view all announcements" on public.site_announcements;
create policy "Authenticated can view all announcements"
  on public.site_announcements
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated can insert announcements" on public.site_announcements;
create policy "Authenticated can insert announcements"
  on public.site_announcements
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated can update announcements" on public.site_announcements;
create policy "Authenticated can update announcements"
  on public.site_announcements
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated can delete announcements" on public.site_announcements;
create policy "Authenticated can delete announcements"
  on public.site_announcements
  for delete
  to authenticated
  using (true);

grant select on table public.site_announcements to anon, authenticated;
grant insert, update, delete on table public.site_announcements to authenticated;

-- ---------------------------------------------------------------------------
-- Gallery (table + public storage bucket)
-- ---------------------------------------------------------------------------

create table if not exists public.gallery_images (
  id bigint generated always as identity primary key,
  storage_path text not null unique,
  image_url text not null,
  caption text,
  alt_text text not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists gallery_images_sort_order_idx
  on public.gallery_images (sort_order, id);

alter table public.gallery_images enable row level security;

drop policy if exists "Public can view active gallery images" on public.gallery_images;
create policy "Public can view active gallery images"
  on public.gallery_images
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Authenticated can view all gallery images" on public.gallery_images;
create policy "Authenticated can view all gallery images"
  on public.gallery_images
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated can insert gallery images" on public.gallery_images;
create policy "Authenticated can insert gallery images"
  on public.gallery_images
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated can update gallery images" on public.gallery_images;
create policy "Authenticated can update gallery images"
  on public.gallery_images
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated can delete gallery images" on public.gallery_images;
create policy "Authenticated can delete gallery images"
  on public.gallery_images
  for delete
  to authenticated
  using (true);

grant select on table public.gallery_images to anon, authenticated;
grant insert, update, delete on table public.gallery_images to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'gallery',
  'gallery',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Public buckets serve files by URL without a SELECT policy.
-- A SELECT policy on storage.objects lets anyone list every file in the bucket.
drop policy if exists "Public can view gallery files" on storage.objects;

drop policy if exists "Authenticated can upload gallery files" on storage.objects;
create policy "Authenticated can upload gallery files"
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'gallery');

drop policy if exists "Authenticated can update gallery files" on storage.objects;
create policy "Authenticated can update gallery files"
  on storage.objects
  for update
  to authenticated
  using (bucket_id = 'gallery')
  with check (bucket_id = 'gallery');

drop policy if exists "Authenticated can delete gallery files" on storage.objects;
create policy "Authenticated can delete gallery files"
  on storage.objects
  for delete
  to authenticated
  using (bucket_id = 'gallery');

-- ---------------------------------------------------------------------------
-- FAQ
-- ---------------------------------------------------------------------------

create table if not exists public.faqs (
  id bigint generated always as identity primary key,
  question text not null,
  answer text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists faqs_sort_order_idx
  on public.faqs (sort_order, id);

alter table public.faqs enable row level security;

drop policy if exists "Public can view active faqs" on public.faqs;
create policy "Public can view active faqs"
  on public.faqs
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Authenticated can view all faqs" on public.faqs;
create policy "Authenticated can view all faqs"
  on public.faqs
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated can insert faqs" on public.faqs;
create policy "Authenticated can insert faqs"
  on public.faqs
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated can update faqs" on public.faqs;
create policy "Authenticated can update faqs"
  on public.faqs
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated can delete faqs" on public.faqs;
create policy "Authenticated can delete faqs"
  on public.faqs
  for delete
  to authenticated
  using (true);

grant select on table public.faqs to anon, authenticated;
grant insert, update, delete on table public.faqs to authenticated;

insert into public.faqs (question, answer, sort_order, is_active)
select *
from (
  values
    (
      'Do I need an appointment?',
      'Walk-ins are welcome, but we recommend scheduling an appointment to ensure minimal wait times and guaranteed availability.',
      1,
      true
    ),
    (
      'How long does a typical wash take?',
      'Most hand washes take between 20–40 minutes depending on the service level and current queue.',
      2,
      true
    ),
    (
      'What makes a hand wash better than an automatic wash?',
      'Hand washing is gentler on your paint, reduces the risk of scratches from hard brushes, and allows us to focus on details machines often miss.',
      3,
      true
    ),
    (
      'Do you offer interior detailing?',
      'Yes, we offer a range of interior services including vacuuming, interior wipe-down, and deep detailing packages.',
      4,
      true
    )
) as seed(question, answer, sort_order, is_active)
where not exists (select 1 from public.faqs);

-- ---------------------------------------------------------------------------
-- About (singleton)
-- ---------------------------------------------------------------------------

create table if not exists public.about_content (
  id bigint primary key default 1 check (id = 1),
  owner_name text not null,
  story_paragraphs text[] not null,
  mission text not null,
  why_choose_us jsonb not null,
  updated_at timestamptz not null default now(),
  constraint about_content_story_len check (cardinality(story_paragraphs) >= 1),
  constraint about_content_why_len check (jsonb_array_length(why_choose_us) = 4)
);

alter table public.about_content enable row level security;

drop policy if exists "Public can view about content" on public.about_content;
create policy "Public can view about content"
  on public.about_content
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can update about content" on public.about_content;
create policy "Authenticated can update about content"
  on public.about_content
  for update
  to authenticated
  using (true)
  with check (true);

grant select on table public.about_content to anon, authenticated;
grant update on table public.about_content to authenticated;

insert into public.about_content (
  id,
  owner_name,
  story_paragraphs,
  mission,
  why_choose_us
)
select
  1,
  'Marcus Reynolds',
  array[
    $p1$Hi, my name is Marcus Reynolds, founder of Onyx Hand Premium Wash. For us, it's not just about washing cars — it's about providing a service you can trust every time you pull in.$p1$,
    $p2$I started Onyx Hand Premium Wash because I saw how many vehicles were being rushed through automated car washes that left scratches, swirl marks, and missed details. As someone who takes pride in a clean vehicle, I believed there should be a better option. That's why I built Onyx Hand Premium Wash around one simple idea: every car deserves careful, premium treatment.$p2$,
    $p3$Instead of conveyor belts and spinning brushes, every vehicle is washed by hand using safe techniques, professional-grade products, and soft microfiber materials that protect your paint while delivering a deep, spotless clean.$p3$
  ],
  $mission$Our mission is to deliver a premium hand wash experience that protects your vehicle while providing unmatched attention to detail. We focus on quality, consistency, and customer satisfaction every time.$mission$,
  $why$[
    {
      "title": "Hand Washed Only",
      "description": "Every vehicle is washed by hand to prevent scratches and ensure a deeper clean.",
      "icon": "hand"
    },
    {
      "title": "Attention to Detail",
      "description": "We clean areas many automated washes miss — wheels, trim, and finishing touches.",
      "icon": "search"
    },
    {
      "title": "Paint-Safe Products",
      "description": "We use high-quality soaps and microfiber materials designed to protect your vehicle's finish.",
      "icon": "shield"
    },
    {
      "title": "Customer First Service",
      "description": "Your satisfaction is our priority, and we take pride in every vehicle we wash.",
      "icon": "handshake"
    }
  ]$why$::jsonb
where not exists (select 1 from public.about_content where id = 1);

-- ---------------------------------------------------------------------------
-- Welcome (singleton)
-- ---------------------------------------------------------------------------

create table if not exists public.welcome_content (
  id bigint primary key default 1 check (id = 1),
  headline text not null,
  tagline text not null,
  intro text not null,
  subheading text not null,
  body_paragraphs text[] not null,
  cta_label text not null,
  cta_href text not null,
  image_path text not null,
  image_alt text not null,
  updated_at timestamptz not null default now(),
  constraint welcome_content_body_len check (cardinality(body_paragraphs) >= 1)
);

alter table public.welcome_content enable row level security;

drop policy if exists "Public can view welcome content" on public.welcome_content;
create policy "Public can view welcome content"
  on public.welcome_content
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated can update welcome content" on public.welcome_content;
create policy "Authenticated can update welcome content"
  on public.welcome_content
  for update
  to authenticated
  using (true)
  with check (true);

grant select on table public.welcome_content to anon, authenticated;
grant update on table public.welcome_content to authenticated;

insert into public.welcome_content (
  id,
  headline,
  tagline,
  intro,
  subheading,
  body_paragraphs,
  cta_label,
  cta_href,
  image_path,
  image_alt
)
select
  1,
  'The Full Onyx Experience',
  'More Than Just a Wash. It''s a Restoration of Pride.',
  $intro$Discover why Onyx is the city's premier destination for 100% hand-car wash excellence. We don't just clean vehicles; we curate an experience designed around your lifestyle and your car's longevity.$intro$,
  'Uncompromising Care for Your Vehicle',
  array[
    $p1$Our signature process utilizes the finest equipment and ultra-premium, soft-touch materials—ensuring a showroom shine without the harsh friction of automated systems.$p1$,
    $p2$From high-gloss finishes to meticulous wheel detailing, our specialists treat every curve of your vehicle with the precision it deserves.$p2$
  ],
  'More About Onyx',
  '/about',
  '/images/carwash-2.jpg',
  'Photo of car'
where not exists (select 1 from public.welcome_content where id = 1);

-- ---------------------------------------------------------------------------
-- Legal (append-only versions)
-- ---------------------------------------------------------------------------

create table if not exists public.legal_documents (
  id bigint generated always as identity primary key,
  slug text not null check (slug in ('privacy', 'terms')),
  title text not null,
  body jsonb not null,
  version integer not null check (version > 0),
  change_summary text not null,
  edited_by uuid references auth.users (id) on delete set null,
  edited_by_email text not null,
  is_current boolean not null default true,
  created_at timestamptz not null default now(),
  unique (slug, version)
);

create unique index if not exists legal_documents_one_current_idx
  on public.legal_documents (slug)
  where is_current;

create index if not exists legal_documents_history_idx
  on public.legal_documents (slug, version desc);

alter table public.legal_documents enable row level security;

drop policy if exists "Public can view current legal documents" on public.legal_documents;
create policy "Public can view current legal documents"
  on public.legal_documents
  for select
  to anon, authenticated
  using (is_current = true);

drop policy if exists "Authenticated can view legal history" on public.legal_documents;
create policy "Authenticated can view legal history"
  on public.legal_documents
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated can publish legal documents" on public.legal_documents;
create policy "Authenticated can publish legal documents"
  on public.legal_documents
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated can retire legal documents" on public.legal_documents;
create policy "Authenticated can retire legal documents"
  on public.legal_documents
  for update
  to authenticated
  using (true)
  with check (true);

grant select on table public.legal_documents to anon, authenticated;
grant insert, update on table public.legal_documents to authenticated;

insert into public.legal_documents (
  slug,
  title,
  body,
  version,
  change_summary,
  edited_by_email,
  is_current
)
select *
from (
  values
    (
      'privacy',
      'Privacy Policy',
      $privacy${
        "type": "doc",
        "content": [
          {
            "type": "paragraph",
            "content": [
              {
                "type": "text",
                "marks": [{ "type": "italic" }],
                "text": "Placeholder. Replace this in Admin → Legal with wording that reflects how the shop handles customer information. This has not been reviewed by a lawyer."
              }
            ]
          }
        ]
      }$privacy$::jsonb,
      1,
      'Initial placeholder content',
      'system@seed',
      true
    ),
    (
      'terms',
      'Terms of Service',
      $terms${
        "type": "doc",
        "content": [
          {
            "type": "paragraph",
            "content": [
              {
                "type": "text",
                "marks": [{ "type": "italic" }],
                "text": "Placeholder. Replace this in Admin → Legal. This has not been reviewed by a lawyer."
              }
            ]
          }
        ]
      }$terms$::jsonb,
      1,
      'Initial placeholder content',
      'system@seed',
      true
    )
) as seed(slug, title, body, version, change_summary, edited_by_email, is_current)
where not exists (select 1 from public.legal_documents);

-- ---------------------------------------------------------------------------
-- Admin profiles
-- ---------------------------------------------------------------------------

create table if not exists public.admin_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  first_name text not null,
  last_name text not null,
  phone text not null,
  job_title text,
  role text not null default 'admin',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_profiles_role_check check (role in ('admin', 'master'))
);

create or replace function public.set_admin_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists admin_profiles_set_updated_at on public.admin_profiles;
create trigger admin_profiles_set_updated_at
  before update on public.admin_profiles
  for each row
  execute function public.set_admin_profiles_updated_at();

-- Users cannot promote themselves. First profile becomes master; later
-- inserts default to admin. Only the service role can change role.
create or replace function public.admin_profiles_protect_role()
returns trigger
language plpgsql
as $$
begin
  if auth.role() is distinct from 'authenticated' then
    return new;
  end if;

  if tg_op = 'INSERT' then
    if exists (
      select 1 from public.admin_profiles where role = 'master'
    ) then
      new.role := 'admin';
    else
      new.role := 'master';
    end if;
  elsif tg_op = 'UPDATE' then
    new.role := old.role;
  end if;

  return new;
end;
$$;

drop trigger if exists admin_profiles_protect_role on public.admin_profiles;
create trigger admin_profiles_protect_role
  before insert or update on public.admin_profiles
  for each row
  execute function public.admin_profiles_protect_role();

alter table public.admin_profiles enable row level security;

drop policy if exists "Admins can view own profile" on public.admin_profiles;
create policy "Admins can view own profile"
  on public.admin_profiles
  for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists "Admins can insert own profile" on public.admin_profiles;
create policy "Admins can insert own profile"
  on public.admin_profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists "Admins can update own profile" on public.admin_profiles;
create policy "Admins can update own profile"
  on public.admin_profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

grant select, insert, update on table public.admin_profiles to authenticated;

-- ---------------------------------------------------------------------------
-- Appointments (admin-only)
-- ---------------------------------------------------------------------------

create table if not exists public.appointment (
  id bigint generated always as identity primary key,
  first_name text not null,
  last_name text,
  customer_name text,
  phone_number text,
  email text,
  service text not null,
  service_id bigint references public.services (id) on delete set null,
  appointment_date timestamptz not null,
  notes text,
  status text not null default 'scheduled',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists appointment_appointment_date_idx
  on public.appointment (appointment_date);

create index if not exists appointment_status_date_idx
  on public.appointment (status, appointment_date);

alter table public.appointment enable row level security;

drop policy if exists "Authenticated can view appointments" on public.appointment;
create policy "Authenticated can view appointments"
  on public.appointment
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated can insert appointments" on public.appointment;
create policy "Authenticated can insert appointments"
  on public.appointment
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated can update appointments" on public.appointment;
create policy "Authenticated can update appointments"
  on public.appointment
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated can delete appointments" on public.appointment;
create policy "Authenticated can delete appointments"
  on public.appointment
  for delete
  to authenticated
  using (true);

revoke all on table public.appointment from anon;
grant select, insert, update, delete on table public.appointment to authenticated;

notify pgrst, 'reload schema';
